name: Playwright Tests with Github Actions

on:
  workflow_dispatch: {}
  schedule:       
    - cron: '0 2 * * *'  # Runs every day at 7:30 AM ITC  

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60         
    strategy:
      matrix:
        shard: [1,2,3]         
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: PlaywrightNPM/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: PlaywrightNPM

      - name: Install Playwright Browsers
        run: npx playwright install chromium
        working-directory: PlaywrightNPM

      - name: Run Playwright tests
        run: npx playwright test runner*.spec.js --shard=${{ matrix.shard }}/3 --reporter=list,html --output=playwright-report/
        working-directory: PlaywrightNPM

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-shard-${{ matrix.shard }}
          path: PlaywrightNPM/playwright-report/
          retention-days: 30

      - name: Deploy Playwright report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./PlaywrightNPM/playwright-report
          destination_dir: playwright-report
    


    
        
  
