name: Playwright Tests with Github Actions

on:
  workflow_dispatch: {}
  schedule:       
    - cron: '0 2 * * *'  # Runs every day at 7:30 AM ITC  

jobs:
  test-and-deploy:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: PlaywrightNPM/package-lock.json

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: PlaywrightNPM

      # 4️⃣ Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install chromium
        working-directory: PlaywrightNPM

      # 5️⃣ Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test runner*.spec.js --reporter=list,html --output=playwright-report/
        working-directory: PlaywrightNPM

      # 6️⃣ Upload HTML report as artifact
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: PlaywrightNPM/playwright-report/
          retention-days: 30

      # 7️⃣ Deploy HTML report to GitHub Pages
      - name: Deploy Playwright report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # automatically provided
          publish_dir: ./PlaywrightNPM/playwright-report
          destination_dir: playwright-report

