name: Playwright Tests with GitHub Actions

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'  # runs every day at 7:30 AM IST

permissions:
  contents: write 

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        shard: [1,2,3]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: PlaywrightNPM/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: PlaywrightNPM

      - name: Install Playwright Browsers
        run: npx playwright install chromium
        working-directory: PlaywrightNPM

      - name: Run Playwright Tests (Shard ${{ matrix.shard }})
        run: npx playwright test runner*.spec.js --shard=${{ matrix.shard }}/3 --reporter=blob
        working-directory: PlaywrightNPM

      - name: Upload Blob Report
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shard }}
          path: PlaywrightNPM/blob-report

  # Merge Shard Reports & Deploy on GitHub Pages
  merge-and-deploy:
    needs: e2e
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: PlaywrightNPM

      - name: Download All Shard Reports
        uses: actions/download-artifact@v4
        with:
          path: PlaywrightNPM/all-blob-reports

      - name: Flatten Blob Reports
        run: |
          mkdir -p PlaywrightNPM/merged-blobs
          find PlaywrightNPM/all-blob-reports -name "*.zip" -exec cp {} PlaywrightNPM/merged-blobs \;

      - name: Merge Reports
        run: npx playwright merge-reports --reporter html ./merged-blobs
        working-directory: PlaywrightNPM

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PlaywrightNPM/playwright-report
          

