name: Playwright Tests with Github Actions

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        shard: [1,2,3]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: PlaywrightNPM/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: PlaywrightNPM

      - name: Install Playwright Browsers
        run: npx playwright install chromium
        working-directory: PlaywrightNPM

      # üî• IMPORTANT: use blob reporter instead of html
      - name: Run Playwright tests (Shard)
        run: npx playwright test runner*.spec.js --shard=${{ matrix.shard }}/3 --reporter=blob
        working-directory: PlaywrightNPM

      - name: Upload blob report
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shard }}
          path: PlaywrightNPM/blob-report

  # üîπ 2Ô∏è‚É£ MERGE + DEPLOY JOB (runs ONCE)
  merge-and-deploy:
    needs: e2e
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: PlaywrightNPM

      - name: Download all blob reports
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports

      - name: Merge reports
        run: |
          npx playwright merge-reports --reporter html ./all-blob-reports
        working-directory: PlaywrightNPM

      - name: Deploy merged report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PlaywrightNPM/playwright-report
          destination_dir: playwright-report
